@StudyCaseWebApi_HostAddress = http://localhost:5288
@jwt_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGFuYWFhQGFkbWluLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiN2RjOGNiMWItODljNy00ZTZjLThhYWYtNGI2MTUxODE5NTI1IiwiZXhwIjoxNzYxMDc3MTIwLCJpc3MiOiJTdHVkeUNhc2VXZWJBcGlJc3N1ZXIifQ.saY8k0qZVxFlDYJGJ6h4TfGT4h2DkYY-a2hOHndujsM

POST http://localhost:5288/api/Authentication/Login
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@admin.com",
  "password": "fcgAdmin123.",
  "isAdmin": true
}

###

POST http://localhost:5288/api/Authentication/Login
Content-Type: application/json

{
  "username": "alanaaa",
  "email": "alanaaa@admin.com",
  "password": "fcgAdmin123."
}

###

POST http://localhost:5288/api/Authentication/CreateAccount
Content-Type: application/json

{
  "username": "alanaaa",
  "email": "alanaaa@admin.com",
  "password": "fcgAdmin123.",
  "isAdmin": true
}

###

POST http://localhost:5288/api/UserCreator/CreateUser
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "username": "Alan",
  "password": "Alan123.",
  "email": "alanfs1010@gmail.com",
  "isAdmin": true
}

###

POST http://localhost:5288/api/UserCreator/CreateUser
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "username": "Alanfsaa",
  "password": "Alan123.aaa",
  "email": "alanfs101aaaaa@gmail.com",
  "isAdmin": false
}

###

POST http://localhost:5288/api/GameCreator/RegisterNewGame
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "id":  "ac72b52c-604f-46e2-b64c-a29e7e26f136",
  "name": "New Game aaa",
  "base_price": "0.5",
  "active": false
}

###

POST http://localhost:5288/graphql
Content-Type: application/json

{
  "query": "query { users { id username } }"
}

###

POST http://localhost:5288/graphql
Content-Type: application/json

{
  "query": "query { userGames(id: \"a4adfbed-4146-4980-89f5-6488c447dc2e\") { id username userGames { user_id game_ids } } }"
}

###

